import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const value = {
    language,
    setLanguage,
    t: (key) => getTranslation(key, language),
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

const getTranslation = (key, lang) => {
  const keys = key.split('.');
  let value = translations[lang];

  for (const k of keys) {
    if (value && value[k]) {
      value = value[k];
    } else {
      // Fallback to English
      value = translations['en'];
      for (const k of keys) {
        if (value && value[k]) {
          value = value[k];
        } else {
          return key;
        }
      }
      return value;
    }
  }
  return value;
};

export const translations = {
  en: {
    nav: {
      problem: 'Problem',
      solution: 'Solution',
      howItWorks: 'How It Works',
      benefits: 'Benefits',
      requestDemo: 'Request Demo',
      startTrial: 'Start Free Trial',
    },
    hero: {
      badge: 'Live Commerce Security System',
      headline1: 'Stop Losing Inventory',
      headline2: 'In Live Sales.',
      subheadline: 'Before it destroys your business. Every year, live sellers lose hundreds of thousands to internal theft, hidden orders, and fake stock records.',
      feature1: 'Track every product',
      feature2: 'Lock every operation',
      feature3: 'Expose every abnormal action',
      feature4: 'Protect every profit',
      requestDemo: 'Request Demo',
      startTrial: 'Start Free Trial',
      dashboard: 'Live Dashboard',
      totalStock: 'Total Stock',
      orders: 'Orders',
      lossRate: 'Loss Rate',
      alerts: 'Alerts',
      allClear: 'All clear',
      liveTracking: 'Live tracking',
      fromAvg: 'from avg',
      today: 'today',
      recentActivity: 'Recent Activity',
      stockVerified: 'Stock verified',
      orderSynced: 'Order synced',
      auditComplete: 'Audit complete',
    },
    problem: {
      label: 'The Hidden Crisis',
      headline1: "Most Live-Selling Companies Don't",
      headline2: 'Collapse Because of Competition',
      subheadline: 'They collapse because of',
      internalLeakage: 'internal leakage',
      bleeding: 'Behind the scenes, your business is bleeding.',
      problems: {
        p1: 'Inventory disappears',
        p2: "Orders don't match shipments",
        p3: '"Sold out" becomes "private deal"',
        p4: 'Samples become personal income',
        p5: 'Data is manipulated',
        p6: 'Management loses control',
      },
      warning: 'Nobody knows who is responsible',
      warningDetail: 'Because the system is broken.',
    },
    painPoints: {
      label: 'Real Problems',
      headline1: 'What Live Sellers Face',
      headline2: 'Every Single Day',
      point1: {
        title: 'Overlapping Roles = Guaranteed Risk',
        description: 'In many companies, one person handles live hosting, customer service, inventory, and shipping. When power overlaps, theft becomes easy — and invisible.',
        details: ['Live hosting', 'Customer service', 'Inventory management', 'Shipping coordination'],
      },
      point2: {
        title: 'Heavy Systems Get Ignored',
        description: 'Traditional "all-in-one" systems are complicated, increase workload, slow employees, and create resistance. So staff bypass them.',
        details: ['Records become fake', 'Control disappears', 'Processes break down'],
      },
      point3: {
        title: 'No Real Audit = No Fear',
        description: 'When employees know nobody checks, logs can be edited, and data is messy — they take risks. Because they think: "I won\'t be caught."',
        details: ['Nobody checks', 'Logs can be edited', 'Data is messy'],
      },
    },
    consequences: {
      label: 'Wake Up Call',
      headline1: 'What Happens If You',
      headline2: "Don't Fix This In Time?",
      subheadline: 'Many founders realize too late.',
      year1: 'First Year',
      quote1: '"Some losses are normal."',
      year2: 'Second Year',
      quote2: '"Why are profits shrinking?"',
      year3: 'Third Year',
      quote3: '"Where did my money go?"',
      discover: 'Then They Discover:',
      c1: 'Inventory worth a house is gone',
      c2: 'Trusted employees are involved',
      c3: 'Evidence is missing',
      c4: 'Legal action is impossible',
      c5: 'Company reputation is damaged',
      c6: 'Cash flow collapses',
      warning: "By then, it's often irreversible.",
      warningDetail: 'Internal theft is not an accident.',
      systemFailure: "It's a system failure.",
    },
    solution: {
      label: 'Our Solution',
      headline1: 'Live Sales',
      headline2: 'Anti-Theft Control System',
      description: 'We don\'t build "big and heavy software." We build',
      highlight: 'Minimum Internal Control Systems',
      forLive: 'for live commerce.',
      tag1: 'Light',
      tag2: 'Strict',
      tag3: 'Unbreakable',
      designedTo: 'Designed to make theft:',
      difficult: 'Difficult',
      risky: 'Risky',
      traceable: 'Traceable',
      notWorthIt: 'Not worth it',
    },
    howItWorks: {
      label: 'How It Works',
      headline1: 'Six Pillars of',
      headline2: 'Total Control',
      feature1: {
        title: 'Inventory Can Only Go Down',
        description: 'No manual increases. No fake restocking. No hidden adjustments.',
        highlight: 'Every deduction is real.',
      },
      feature2: {
        title: 'Every Action Is Recorded',
        description: 'Each change includes time, channel (Live/Private/Platform), operator, and device.',
        highlight: 'No excuses. Only facts.',
        details: ['Time', 'Channel', 'Operator', 'Device'],
      },
      feature3: {
        title: 'Role Separation Built-In',
        description: 'One person = One role. Host ≠ Warehouse. Sales ≠ Inventory. Finance ≠ Shipping.',
        highlight: 'No more "one person controls everything."',
      },
      feature4: {
        title: 'Works With Your Existing Tools',
        description: 'We integrate with ManyChat, Wazzup, amoCRM, and other platforms.',
        highlight: 'Only reconciliation is allowed. No direct manipulation.',
      },
      feature5: {
        title: 'Automatic Risk Alerts',
        description: 'Detects abnormal conversion rates, strange return patterns, "always sold out" SKUs.',
        highlight: 'Know the risk before it explodes.',
      },
      feature6: {
        title: 'Boss-Only Control Panel',
        description: 'Real-time overview: Stock, Orders, Loss rate, Abnormal actions.',
        highlight: 'No filtering. No beautification. Only reality.',
      },
    },
    benefits: {
      label: 'Why Choose Us',
      headline1: 'Why Companies',
      headline2: 'Choose Our System',
      benefit1: {
        title: 'Not More Management. Real Control.',
        description: "You don't need to watch everyone. The system watches for you.",
      },
      benefit2: {
        title: 'Not More Work. Less Chaos.',
        description: 'Simple operations. No unnecessary steps. Employees actually use it.',
      },
      benefit3: {
        title: 'Not Just Software. Risk Protection.',
        description: 'We don\'t sell "features." We sell security.',
      },
      benefit4: {
        title: 'ROI from Day One',
        description: 'If you reduce losses by just 20%, the system pays for itself many times over.',
      },
      cta: 'Get Started Today',
    },
    socialProof: {
      label: 'Real Impact',
      headline1: 'What Our Clients',
      headline2: 'Report',
      subheadline: 'Because control creates confidence.',
      stat1: { value: '30-60%', label: 'Reduction in inventory loss' },
      stat2: { value: '100%', label: 'Clear responsibility chains' },
      stat3: { value: '3x', label: 'Stronger discipline' },
      stat4: { value: '95%', label: 'Higher trust in data' },
      stat5: { value: '2x', label: 'Better decision-making' },
      stat6: { value: '∞', label: 'Stable growth potential' },
      quote: 'We thought we had good controls. After implementing this system, we discovered we were losing',
      quoteHighlight: '23% more inventory',
      quoteEnd: 'than we thought. Now our loss rate is under 1%.',
      quoteAuthor: '— Live Commerce Business Owner',
    },
    philosophy: {
      label: 'Our Philosophy',
      headline1: 'Systems Exist to',
      headline2: 'Leave Evidence',
      subheadline: 'Rules exist to restrain human nature.',
      dontRelyOn: "We don't rely on",
      goodPeople: '"Good People"',
      relyOn: 'We rely on',
      goodSystems: 'Good Systems',
    },
    targetUsers: {
      label: 'Who Is This For?',
      headline1: 'Built for',
      headline2: 'Live Sellers',
      user1: 'Live commerce companies',
      user2: 'TikTok / Shopee / Taobao sellers',
      user3: 'Social commerce teams',
      user4: 'Multi-host studios',
      user5: 'Growing brands',
      user6: 'Founders who care about long-term survival',
      tagline: 'If you sell live — you need control.',
    },
    cta: {
      label: 'Take Action Now',
      headline1: 'Stop Guessing.',
      headline2: 'Start Knowing.',
      subheadline: 'Every day without control is another day of silent loss.',
      protect1: 'Protect your inventory',
      protect2: 'Protect your profits',
      protect3: 'Protect your company',
      riskAssessment: 'Book Free Risk Assessment',
      requestDemo: 'Request a Demo',
      talkExperts: 'Talk to Our Experts',
    },
    footer: {
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      contact: 'Contact',
      rights: 'All rights reserved.',
    },
  },
  kz: {
    nav: {
      problem: 'Мәселе',
      solution: 'Шешім',
      howItWorks: 'Қалай жұмыс істейді',
      benefits: 'Артықшылықтар',
      requestDemo: 'Сынап көру',
      startTrial: 'Тегін бастау',
    },
    hero: {
      badge: 'Тікелей сауда қауіпсіздік жүйесі',
      headline1: 'Тауар қорын жоғалтуды',
      headline2: 'Тоқтатыңыз.',
      subheadline: 'Бизнесіңізді құлатпас бұрын. Жыл сайын тікелей сатушылар ішкі ұрлық, жасырын тапсырыстар және жалған қор жазбалары салдарынан жүз мыңдаған қаражат жоғалтады.',
      feature1: 'Әр өнімді қадағалау',
      feature2: 'Әр операцияны құлыптау',
      feature3: 'Әр қалыптан тыс әрекетті анықтау',
      feature4: 'Әр пайданы қорғау',
      requestDemo: 'Сынап көру ',
      startTrial: 'Тегін бастау',
      dashboard: 'Тікелей бақылау тақтасы',
      totalStock: 'Жалпы қор',
      orders: 'Тапсырыстар',
      lossRate: 'Жоғалту деңгейі',
      alerts: 'Ескертулер',
      allClear: 'Бәрі таза',
      liveTracking: 'Тікелей бақылау',
      fromAvg: 'орташадан',
      today: 'бүгін',
      recentActivity: 'Соңғы белсенділік',
      stockVerified: 'Қор тексерілді',
      orderSynced: 'Тапсырыс синхрондалды',
      auditComplete: 'Аудит аяқталды',
    },
    problem: {
      label: 'Жасырын дағдарыс',
      headline1: 'Тікелей сатудағы компаниялардың көбі',
      headline2: 'Бәсекелестіктен емес құлайды',
      subheadline: 'Олар құлайды',
      internalLeakage: 'ішкі ағып кетуден',
      bleeding: 'Сахна артында сіздің бизнесіңіз қан кетуде.',
      problems: {
        p1: 'Тауар қоры жоғалады',
        p2: 'Тапсырыстар жеткізілімге сәйкес келмейді',
        p3: '"Сатылып кетті" "жеке мәміле" болады',
        p4: 'Үлгілер жеке табысқа айналады',
        p5: 'Деректер бұрмаланады',
        p6: 'Басшылық бақылауды жоғалтады',
      },
      warning: 'Кім жауапты екенін ешкім білмейді',
      warningDetail: 'Себебі жүйе бұзылған.',
    },
    painPoints: {
      label: 'Нақты мәселелер',
      headline1: 'Тікелей сатушылар күн сайын',
      headline2: 'Немен кездеседі',
      point1: {
        title: 'Рөлдердің қабаттасуы = Кепілдендірілген тәуекел',
        description: 'Көптеген компанияларда бір адам тікелей эфирді, клиенттерге қызмет көрсетуді, қор мен жеткізуді басқарады. Билік қабаттасқанда ұрлық оңай және көрінбейтін болады.',
        details: ['Тікелей эфир', 'Клиенттерге қызмет', 'Қор басқару', 'Жеткізу үйлестіру'],
      },
      point2: {
        title: 'Ауыр жүйелер еленбейді',
        description: 'Дәстүрлі "бәрі біреуінде" жүйелер күрделі, жұмыс жүктемесін арттырады, қызметкерлерді баяулатады және қарсылық тудырады. Сондықтан қызметкерлер оларды айналып өтеді.',
        details: ['Жазбалар жалған болады', 'Бақылау жоғалады', 'Процестер бұзылады'],
      },
      point3: {
        title: 'Нақты аудит жоқ = Қорқыныш жоқ',
        description: 'Қызметкерлер ешкім тексермейтінін, журналдарды өзгертуге болатынын және деректер шатасып кеткенін білгенде — олар тәуекелге барады. Себебі олар: "Мені ұстамайды" деп ойлайды.',
        details: ['Ешкім тексермейді', 'Журналдарды өңдеуге болады', 'Деректер шатасқан'],
      },
    },
    consequences: {
      label: 'Оянар шақ',
      headline1: 'Мұны уақытында',
      headline2: 'Түзетпесеңіз не болады?',
      subheadline: 'Көптеген негізін қалаушылар тым кеш түсінеді.',
      year1: 'Бірінші жыл',
      quote1: '"Кейбір жоғалтулар қалыпты."',
      year2: 'Екінші жыл',
      quote2: '"Неге пайда азайып барады?"',
      year3: 'Үшінші жыл',
      quote3: '"Ақшам қайда кетті?"',
      discover: 'Содан кейін олар ашады:',
      c1: 'Үйге тұрарлық тауар қоры жоғалды',
      c2: 'Сенімді қызметкерлер қатысты',
      c3: 'Дәлелдер жоқ',
      c4: 'Құқықтық шара мүмкін емес',
      c5: 'Компания беделі зардап шекті',
      c6: 'Ақша ағыны құлдырады',
      warning: 'Сол кезде бұл жиі қайтымсыз болады.',
      warningDetail: 'Ішкі ұрлық кездейсоқ емес.',
      systemFailure: 'Бұл жүйе ақауы.',
    },
    solution: {
      label: 'Біздің шешім',
      headline1: 'Тікелей сатуда',
      headline2: 'Ұрлыққа қарсы бақылау жүйесі',
      description: 'Біз "үлкен және ауыр бағдарламалық жасақтама" жасамаймыз. Біз жасаймыз',
      highlight: 'Минималды ішкі бақылау жүйелері',
      forLive: 'тікелей сауда үшін.',
      tag1: 'Жеңіл',
      tag2: 'Қатаң',
      tag3: 'Бұзылмайтын',
      designedTo: 'Ұрлықты мынадай ету үшін жасалған:',
      difficult: 'Қиын',
      risky: 'Қауіпті',
      traceable: 'Бақылауға болатын',
      notWorthIt: 'Тұрарлық емес',
    },
    howItWorks: {
      label: 'Қалай жұмыс істейді',
      headline1: 'Толық бақылаудың',
      headline2: 'Алты тірегі',
      feature1: {
        title: 'Тауар қоры тек азая алады',
        description: 'Қолмен арттыру жоқ. Жалған толықтыру жоқ. Жасырын түзетулер жоқ.',
        highlight: 'Әр шегеру нақты.',
      },
      feature2: {
        title: 'Әр әрекет жазылады',
        description: 'Әр өзгеріс уақытты, арнаны (Тікелей/Жеке/Платформа), операторды және құрылғыны қамтиды.',
        highlight: 'Сылтау жоқ. Тек фактілер.',
        details: ['Уақыт', 'Арна', 'Оператор', 'Құрылғы'],
      },
      feature3: {
        title: 'Рөлдерді бөлу орнатылған',
        description: 'Бір адам = Бір рөл. Жүргізуші ≠ Қойма. Сату ≠ Қор. Қаржы ≠ Жеткізу.',
        highlight: '"Бір адам бәрін басқарады" болмайды.',
      },
      feature4: {
        title: 'Бар құралдарыңызбен жұмыс істейді',
        description: 'Біз ManyChat, Wazzup, amoCRM және басқа платформалармен интеграцияланамыз.',
        highlight: 'Тек салыстыруға рұқсат. Тікелей манипуляция жоқ.',
      },
      feature5: {
        title: 'Автоматты тәуекел ескертулері',
        description: 'Қалыптан тыс конверсия көрсеткіштерін, оғаш қайтару үлгілерін, "әрқашан сатылып кеткен" SKU-ларды анықтайды.',
        highlight: 'Тәуекелді жарылмай тұрып біліңіз.',
      },
      feature6: {
        title: 'Тек бастыққа арналған басқару тақтасы',
        description: 'Нақты уақыттағы шолу: Қор, Тапсырыстар, Жоғалту деңгейі, Қалыптан тыс әрекеттер.',
        highlight: 'Сүзгілеу жоқ. Әсемдеу жоқ. Тек шындық.',
      },
    },
    benefits: {
      label: 'Неге бізді таңдайды',
      headline1: 'Неге компаниялар',
      headline2: 'Біздің жүйені таңдайды',
      benefit1: {
        title: 'Көбірек басқару емес. Нақты бақылау.',
        description: 'Сізге барлығын бақылау қажет емес. Жүйе сіз үшін бақылайды.',
      },
      benefit2: {
        title: 'Көбірек жұмыс емес. Азырақ хаос.',
        description: 'Қарапайым операциялар. Қажетсіз қадамдар жоқ. Қызметкерлер оны шынымен пайдаланады.',
      },
      benefit3: {
        title: 'Тек бағдарламалық жасақтама емес. Тәуекелден қорғау.',
        description: 'Біз "функциялар" сатпаймыз. Біз қауіпсіздік сатамыз.',
      },
      benefit4: {
        title: 'Бірінші күннен ROI',
        description: 'Жоғалтуларды тек 20% азайтсаңыз, жүйе өзін бірнеше рет өтейді.',
      },
      cta: 'Бүгін бастаңыз',
    },
    socialProof: {
      label: 'Нақты әсер',
      headline1: 'Клиенттеріміз не',
      headline2: 'Хабарлайды',
      subheadline: 'Себебі бақылау сенім тудырады.',
      stat1: { value: '30-60%', label: 'Тауар қорын жоғалтуды азайту' },
      stat2: { value: '100%', label: 'Нақты жауапкершілік тізбегі' },
      stat3: { value: '3x', label: 'Күшейтілген тәртіп' },
      stat4: { value: '95%', label: 'Деректерге жоғары сенім' },
      stat5: { value: '2x', label: 'Жақсартылған шешім қабылдау' },
      stat6: { value: '∞', label: 'Тұрақты өсу әлеуеті' },
      quote: 'Біз жақсы бақылаумыз бар деп ойладық. Осы жүйені енгізгеннен кейін біз ойлағанымыздан',
      quoteHighlight: '23% көбірек тауар қорын жоғалтып жатқанымызды',
      quoteEnd: 'анықтадық. Енді жоғалту деңгейіміз 1%-дан төмен.',
      quoteAuthor: '— Тікелей сауда бизнес иесі',
    },
    philosophy: {
      label: 'Біздің философия',
      headline1: 'Жүйелер',
      headline2: 'Дәлел қалдыру үшін бар',
      subheadline: 'Ережелер адам табиғатын тежеу үшін бар.',
      dontRelyOn: 'Біз сенбейміз',
      goodPeople: '"Жақсы адамдарға"',
      relyOn: 'Біз сенеміз',
      goodSystems: 'Жақсы жүйелерге',
    },
    targetUsers: {
      label: 'Бұл кімге арналған?',
      headline1: 'Жасалған',
      headline2: 'Тікелей сатушылар үшін',
      user1: 'Тікелей сауда компаниялары',
      user2: 'TikTok / Shopee / Taobao сатушылары',
      user3: 'Әлеуметтік сауда топтары',
      user4: 'Көп жүргізушілі студиялар',
      user5: 'Дамып келе жатқан брендтер',
      user6: 'Ұзақ мерзімді өмір сүруге мән беретін негізін қалаушылар',
      tagline: 'Егер сіз тікелей сатсаңыз — сізге бақылау керек.',
    },
    cta: {
      label: 'Қазір әрекет етіңіз',
      headline1: 'Болжауды тоқтатыңыз.',
      headline2: 'Білуді бастаңыз.',
      subheadline: 'Бақылаусыз әр күн — тағы бір үнсіз жоғалту күні.',
      protect1: 'Тауар қорыңызды қорғаңыз',
      protect2: 'Пайдаңызды қорғаңыз',
      protect3: 'Компанияңызды қорғаңыз',
      riskAssessment: 'Тегін тәуекел бағалауын брондаңыз',
      requestDemo: 'Сынап көру',
      talkExperts: 'Сарапшылармен сөйлесіңіз',
    },
    footer: {
      privacy: 'Құпиялылық саясаты',
      terms: 'Қызмет көрсету шарттары',
      contact: 'Байланыс',
      rights: 'Барлық құқықтар қорғалған.',
    },
  },
  ru: {
    nav: {
      problem: 'Проблема',
      solution: 'Решение',
      howItWorks: 'Как это работает',
      benefits: 'Преимущества',
      requestDemo: 'Запросить демо',
      startTrial: 'Начать бесплатно',
    },
    hero: {
      badge: 'Система безопасности для лайв-коммерции',
      headline1: 'Прекратите терять товар',
      headline2: 'В прямых продажах.',
      subheadline: 'Пока это не разрушило ваш бизнес. Каждый год продавцы в прямом эфире теряют сотни тысяч из-за внутреннего воровства, скрытых заказов и поддельных складских записей.',
      feature1: 'Отслеживание каждого товара',
      feature2: 'Блокировка каждой операции',
      feature3: 'Выявление каждого аномального действия',
      feature4: 'Защита каждой прибыли',
      requestDemo: 'Запросить демо',
      startTrial: 'Начать бесплатно',
      dashboard: 'Панель мониторинга',
      totalStock: 'Общий запас',
      orders: 'Заказы',
      lossRate: 'Уровень потерь',
      alerts: 'Оповещения',
      allClear: 'Всё в норме',
      liveTracking: 'Отслеживание',
      fromAvg: 'от среднего',
      today: 'сегодня',
      recentActivity: 'Последняя активность',
      stockVerified: 'Запас проверен',
      orderSynced: 'Заказ синхронизирован',
      auditComplete: 'Аудит завершён',
    },
    problem: {
      label: 'Скрытый кризис',
      headline1: 'Большинство компаний в лайв-продажах',
      headline2: 'Разваливаются не из-за конкуренции',
      subheadline: 'Они разваливаются из-за',
      internalLeakage: 'внутренней утечки',
      bleeding: 'За кулисами ваш бизнес истекает кровью.',
      problems: {
        p1: 'Товар исчезает',
        p2: 'Заказы не соответствуют отгрузкам',
        p3: '"Распродано" становится "частной сделкой"',
        p4: 'Образцы становятся личным доходом',
        p5: 'Данные манипулируются',
        p6: 'Руководство теряет контроль',
      },
      warning: 'Никто не знает, кто виноват',
      warningDetail: 'Потому что система сломана.',
    },
    painPoints: {
      label: 'Реальные проблемы',
      headline1: 'С чем сталкиваются продавцы',
      headline2: 'Каждый день',
      point1: {
        title: 'Перекрытие ролей = Гарантированный риск',
        description: 'Во многих компаниях один человек занимается эфиром, обслуживанием клиентов, складом и доставкой. Когда полномочия пересекаются, воровство становится лёгким — и невидимым.',
        details: ['Ведение эфира', 'Обслуживание клиентов', 'Управление складом', 'Координация доставки'],
      },
      point2: {
        title: 'Тяжёлые системы игнорируются',
        description: 'Традиционные системы "всё в одном" сложные, увеличивают нагрузку, замедляют сотрудников и вызывают сопротивление. Поэтому персонал их обходит.',
        details: ['Записи становятся фальшивыми', 'Контроль исчезает', 'Процессы ломаются'],
      },
      point3: {
        title: 'Нет реального аудита = Нет страха',
        description: 'Когда сотрудники знают, что никто не проверяет, логи можно редактировать, а данные в беспорядке — они рискуют. Потому что думают: "Меня не поймают."',
        details: ['Никто не проверяет', 'Логи можно редактировать', 'Данные в беспорядке'],
      },
    },
    consequences: {
      label: 'Тревожный звонок',
      headline1: 'Что произойдёт, если вы',
      headline2: 'Не исправите это вовремя?',
      subheadline: 'Многие основатели понимают слишком поздно.',
      year1: 'Первый год',
      quote1: '"Некоторые потери — это нормально."',
      year2: 'Второй год',
      quote2: '"Почему прибыль сокращается?"',
      year3: 'Третий год',
      quote3: '"Куда делись мои деньги?"',
      discover: 'А потом они обнаруживают:',
      c1: 'Товар на стоимость дома исчез',
      c2: 'Доверенные сотрудники замешаны',
      c3: 'Доказательства отсутствуют',
      c4: 'Судебный иск невозможен',
      c5: 'Репутация компании подорвана',
      c6: 'Денежный поток рушится',
      warning: 'К тому моменту это часто необратимо.',
      warningDetail: 'Внутреннее воровство — это не случайность.',
      systemFailure: 'Это системный сбой.',
    },
    solution: {
      label: 'Наше решение',
      headline1: 'Система контроля',
      headline2: 'Против воровства в лайв-продажах',
      description: 'Мы не создаём "большое и тяжёлое ПО". Мы создаём',
      highlight: 'Минимальные системы внутреннего контроля',
      forLive: 'для лайв-коммерции.',
      tag1: 'Лёгкая',
      tag2: 'Строгая',
      tag3: 'Несломимая',
      designedTo: 'Разработана, чтобы воровство стало:',
      difficult: 'Сложным',
      risky: 'Рискованным',
      traceable: 'Отслеживаемым',
      notWorthIt: 'Невыгодным',
    },
    howItWorks: {
      label: 'Как это работает',
      headline1: 'Шесть столпов',
      headline2: 'Полного контроля',
      feature1: {
        title: 'Запас может только уменьшаться',
        description: 'Никаких ручных увеличений. Никаких фиктивных пополнений. Никаких скрытых корректировок.',
        highlight: 'Каждое списание реально.',
      },
      feature2: {
        title: 'Каждое действие записывается',
        description: 'Каждое изменение включает время, канал (Эфир/Личные/Платформа), оператора и устройство.',
        highlight: 'Никаких отговорок. Только факты.',
        details: ['Время', 'Канал', 'Оператор', 'Устройство'],
      },
      feature3: {
        title: 'Разделение ролей встроено',
        description: 'Один человек = Одна роль. Ведущий ≠ Склад. Продажи ≠ Запас. Финансы ≠ Доставка.',
        highlight: '"Один человек контролирует всё" больше не работает.',
      },
      feature4: {
        title: 'Работает с вашими инструментами',
        description: 'Мы интегрируемся с ManyChat, Wazzup, amoCRM и другими платформами.',
        highlight: 'Разрешена только сверка. Никаких прямых манипуляций.',
      },
      feature5: {
        title: 'Автоматические оповещения о рисках',
        description: 'Обнаруживает аномальные показатели конверсии, странные паттерны возвратов, "всегда распроданные" SKU.',
        highlight: 'Узнайте о риске до того, как он взорвётся.',
      },
      feature6: {
        title: 'Панель управления только для босса',
        description: 'Обзор в реальном времени: Запас, Заказы, Уровень потерь, Аномальные действия.',
        highlight: 'Без фильтрации. Без приукрашивания. Только реальность.',
      },
    },
    benefits: {
      label: 'Почему выбирают нас',
      headline1: 'Почему компании',
      headline2: 'Выбирают нашу систему',
      benefit1: {
        title: 'Не больше управления. Реальный контроль.',
        description: 'Вам не нужно следить за всеми. Система следит за вас.',
      },
      benefit2: {
        title: 'Не больше работы. Меньше хаоса.',
        description: 'Простые операции. Никаких лишних шагов. Сотрудники действительно используют её.',
      },
      benefit3: {
        title: 'Не просто ПО. Защита от рисков.',
        description: 'Мы продаём не "функции". Мы продаём безопасность.',
      },
      benefit4: {
        title: 'ROI с первого дня',
        description: 'Если вы сократите потери всего на 20%, система окупится многократно.',
      },
      cta: 'Начать сегодня',
    },
    socialProof: {
      label: 'Реальное влияние',
      headline1: 'Что сообщают',
      headline2: 'Наши клиенты',
      subheadline: 'Потому что контроль создаёт уверенность.',
      stat1: { value: '30-60%', label: 'Сокращение потерь запаса' },
      stat2: { value: '100%', label: 'Чёткие цепочки ответственности' },
      stat3: { value: '3x', label: 'Усиленная дисциплина' },
      stat4: { value: '95%', label: 'Высокое доверие к данным' },
      stat5: { value: '2x', label: 'Лучшее принятие решений' },
      stat6: { value: '∞', label: 'Стабильный потенциал роста' },
      quote: 'Мы думали, что у нас хороший контроль. После внедрения этой системы мы обнаружили, что теряли',
      quoteHighlight: 'на 23% больше товара',
      quoteEnd: ', чем думали. Теперь наш уровень потерь ниже 1%.',
      quoteAuthor: '— Владелец бизнеса лайв-коммерции',
    },
    philosophy: {
      label: 'Наша философия',
      headline1: 'Системы существуют, чтобы',
      headline2: 'Оставлять улики',
      subheadline: 'Правила существуют, чтобы сдерживать человеческую природу.',
      dontRelyOn: 'Мы не полагаемся на',
      goodPeople: '"Хороших людей"',
      relyOn: 'Мы полагаемся на',
      goodSystems: 'Хорошие системы',
    },
    targetUsers: {
      label: 'Для кого это?',
      headline1: 'Создано для',
      headline2: 'Продавцов в прямом эфире',
      user1: 'Компании лайв-коммерции',
      user2: 'Продавцы TikTok / Shopee / Taobao',
      user3: 'Команды социальной коммерции',
      user4: 'Студии с несколькими ведущими',
      user5: 'Растущие бренды',
      user6: 'Основатели, которым важно долгосрочное выживание',
      tagline: 'Если вы продаёте в прямом эфире — вам нужен контроль.',
    },
    cta: {
      label: 'Действуйте сейчас',
      headline1: 'Хватит гадать.',
      headline2: 'Начните знать.',
      subheadline: 'Каждый день без контроля — ещё один день тихих потерь.',
      protect1: 'Защитите ваш товар',
      protect2: 'Защитите вашу прибыль',
      protect3: 'Защитите вашу компанию',
      riskAssessment: 'Бесплатная оценка рисков',
      requestDemo: 'Запросить демо',
      talkExperts: 'Поговорить с экспертами',
    },
    footer: {
      privacy: 'Политика конфиденциальности',
      terms: 'Условия использования',
      contact: 'Контакты',
      rights: 'Все права защищены.',
    },
  },
};

export default LanguageContext;
